version: 1.0.{build}
image: Ubuntu2204
environment:
  APP_PORT: 3333
  JWT_SECRET: testing
  JWT_EXPIRATION_TIME: 7d
  DOCS_URL: https://github.com/DiegoVictor/bethehero-api#errors-reference
install:
  - sh: npm ci
test_script:
  - sh: npm run test
on_success:
  - sh: |
      curl -Os https://uploader.codecov.io/latest/linux/codecov

      chmod +x codecov
      ./codecov
